# Generated by Django 4.2.1 on 2023-05-27 23:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('hash', models.CharField(default=api.models.generate_hash, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('original_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('city', models.CharField(max_length=85)),
                ('country', models.CharField(max_length=56)),
                ('region', models.CharField(max_length=85)),
                ('timezone', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='api.url')),
            ],
        ),
    ]
