# Generated by Django 4.2.1 on 2023-05-30 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_visitor_date_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='ip_address',
        ),
    ]
