name: Deploy using AWS SSM Send-Command
on:
  push:
    branches: [main]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Server
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1
          instance-ids: ${{ secrets.SERVER_INSTANCE_ID }}
          comment: Deploy the main branch
          working-directory: /home/ubuntu/url-shortener
          command: sudo git pull origin main && /bin/sh ./deploy.sh

      - name: Deploy Worker
        uses: peterkimzz/aws-ssm-send-command@v1.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: us-east-1
          instance-ids: ${{ secrets.WORKER_INSTANCE_ID }}
          comment: Deploy the main branch
          working-directory: /home/ubuntu/url-shortener
          command: sudo git pull origin main && /bin/sh ./worker_deploy.sh
